chore: Remove extraneous unmanaged files
Reference: https://github.com/Kong/terraform-provider-konnect/pull/159

Within Speakeasy, we have some testing automation for generator changes to verify them against real repositories. For some reason, these unmanaged files were not playing nice with that automation:

```
  INFO    Running command: go build ./...	{"path":"/tmp/snapshot-test/d043b1f95db7b2dd"}
  WARN    failed running commands:

  # github.com/kong/terraform-provider-konnect/v2/internal/provider/types
  Error: internal/provider/types/create_aws_vpc_peering_gateway.go:11:33: undefined: AwsVpcPeeringGatewayAttachmentConfig
  # github.com/kong/terraform-provider-konnect/v2/internal/sdk/models/shared
  Error: internal/sdk/models/shared/createawsvpcpeeringgateway.go:16:33: undefined: AwsVpcPeeringGatewayAttachmentConfig
  Error: internal/sdk/models/shared/createawsvpcpeeringgateway.go:40:74: undefined: AwsVpcPeeringGatewayAttachmentConfig
  Error: internal/sdk/models/shared/createawsvpcpeeringgateway.go:42:10: undefined: AwsVpcPeeringGatewayAttachmentConfig

  Error: exit status 1
```

It looks like they may have been accidentally introduced as part of some other refactoring work. You can confirm they are unmanaged via the `.speakeasy/gen.lock` file `generatedFiles` section, which has all files the generator is currently managing. The provider code still builds via `go build .`.